<?php

/**
 * Implements hook_wysiwyg_plugin().
 *
 */
function ccit_accordion_wysiwyg_plugin($editor, $version) {
    $plugins = array();
    switch ($editor) {
        case 'ckeditor':
            if ($version > 4) {
                $plugins['accordion'] = array(
                    'path' => drupal_get_path('module', 'ccit_accordion') . '/plugins/accordion',
                    'filename' => 'plugin.js',
                    'load' => TRUE,
                    'buttons' => array(
                        'accordion' => t('Accordion'),
                    ),
                );
            }
            break;
    }
    return $plugins;
}

function ccit_accordion_init() {
    $path = drupal_get_path('module', 'ccit_accordion');
    drupal_add_js($path . '/accordion.js', 'file');
}
?>
